/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package antprogram;

import javax.swing.table.DefaultTableModel;
import java.util.Date;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.awt.print.PrinterException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class CustomerForm extends javax.swing.JFrame {

    static float tp = 0;
    Statement stmt;
    PreparedStatement pst;

    private MedicineBLL medbll;
    private MedicineDAL meddal;
    private FeedBLL fedbll;
    private FeedDAL feddal;

    private Connection connection;

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
    }

    public CustomerForm(Connection connection) {
        this();
        this.connection = connection;
    }

    public CustomerForm(MedicineBLL medbll, FeedBLL fedbll, Connection connection) {
        this();
        this.medbll = medbll;
        this.fedbll = fedbll;
        this.connection = connection;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustMed = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustFeed = new javax.swing.JTable();
        btnCustFeedCon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCustMedCon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBarCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUY..");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 112, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INVOICE..");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FEEDS..");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tblInvoice.setBackground(new java.awt.Color(204, 204, 204));
        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "bar code", "quantity", "price", "total price"
            }
        ));
        tblInvoice.setToolTipText("");
        tblInvoice.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblInvoice);
        tblInvoice.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 550, 210));

        tblCustMed.setBackground(new java.awt.Color(204, 204, 204));
        tblCustMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustMedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustMed);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 560, 200));

        tblCustFeed.setBackground(new java.awt.Color(204, 204, 204));
        tblCustFeed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustFeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustFeedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCustFeed);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 560, 210));

        btnCustFeedCon.setBackground(new java.awt.Color(124, 193, 238));
        btnCustFeedCon.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnCustFeedCon.setForeground(new java.awt.Color(0, 0, 81));
        btnCustFeedCon.setText("CONNECT");
        btnCustFeedCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustFeedConActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustFeedCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUNTITY :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 380, 30));

        btnSave.setBackground(new java.awt.Color(124, 193, 238));
        btnSave.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 81));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 520, 110, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 380, 30));

        btnAdd.setBackground(new java.awt.Color(124, 193, 238));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 81));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 110, -1));

        btnDelete.setBackground(new java.awt.Color(124, 193, 238));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 81));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        btnCustMedCon.setBackground(new java.awt.Color(124, 193, 238));
        btnCustMedCon.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnCustMedCon.setForeground(new java.awt.Color(0, 0, 81));
        btnCustMedCon.setText("CONNECT");
        btnCustMedCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustMedConActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustMedCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MEDICINE..");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BAR-CODE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        txtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 380, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NAME :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NAME :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 380, 30));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 380, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PRICE :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustFeedConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustFeedConActionPerformed
        try {
            ResultSet fed = (ResultSet) fedbll.getAllFeeds();
            tblCustFeed.setModel(DbUtils.resultSetToTableModel(fed));

        } catch (Exception ex) {
            ex.printStackTrace();
        }

//        try {
//            fedbll.getAllFeeds();
//        } catch (BusinessException ex) {
//            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_btnCustFeedConActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();

        int numOfbill = 1;
        String custID = "12345678901233";
        String date = java.time.LocalDate.now().toString();
        Date date2 = new Date();
        JOptionPane.showMessageDialog(this, date+"\n"+date2);
        try {
        stmt = connection.createStatement();
        //String query = "INSERT INTO tblInvoice VALUES (" + numOfbill + ",'" + date + "','" + custID + "'," + tp + ")";
           String query = "INSERT INTO tblInvoice VALUES (1,'2023-05-25','12345678901233',24324324)";

            stmt.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }

//        for (int count = 0; count < model.getRowCount(); count++) {
//            String barCode = model.getValueAt(count, 1).toString();
//            int quantity = Integer.parseInt(model.getValueAt(count, 1).toString());
//
//            try {
//                stmt = connection.createStatement();
//                String query1 = "INSERT INTO tblInvoiceContent VALUES ('" + barCode + "'," + quantity + "," + numOfbill + ")";
//                stmt.executeUpdate(query1);
//            } catch (SQLException ex) {
//                Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
//            }

  //      }

        // JOptionPane.showMessageDialog(this, totalPrice);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        //tblInvoice.setValueAt(evt, ERROR, NORMAL);
//        int row = tblCustMed.getSelectedRow();
//        String barcode = tblCustMed.getValueAt(row, 0).toString();
//        String name = tblCustMed.getValueAt(row, 9).toString();
//        txtBarCode.setText(barcode);
//        txtName.setText(name);

        String name, barcode;
        int quantity;

        float totalprice, price;
        name = txtName.getText();
        barcode = txtBarCode.getText();
        quantity = Integer.parseInt(txtQuantity.getText());
        price = Float.parseFloat(txtPrice.getText());
        totalprice = quantity * price;
        tp += totalprice;
        Object[] row = {name, barcode, quantity, price, totalprice};
        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        model.addRow(row);


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // int  rows = tblInvoice.getSelectedRows();

        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        int selectRowIndex = tblInvoice.getSelectedRow();
        //JOptionPane.showMessageDialog(this, selectRowIndex);
        model.removeRow(tblInvoice.getSelectedRow());


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCustMedConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustMedConActionPerformed

        try {
            ResultSet med = (ResultSet) medbll.getAllMedicine();
            tblCustMed.setModel(DbUtils.resultSetToTableModel(med));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
//        
//        try {
//            st =connection.createStatement();
//            ResultSet res = st.executeQuery("select * from tblMedicine");
//            tblCustMed.setModel(DbUtils.resultSetToTableModel(res));
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }

    }//GEN-LAST:event_btnCustMedConActionPerformed

    private void txtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarCodeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        //        try {
//            // TODO add your handling code here:
//            statment = dbconnection.createStatement();
//            ResultSet res = statment.executeQuery("SELECT * from tblMedicine");
//
//            tblCustMed.setModel(DbUtils.resultSetToTableModel(res));
//
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
        try {
            DBConnection db = new DBConnection();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowActivated

    private void tblCustMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustMedMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblCustMed.getModel();
        int selectRowIndex = tblCustMed.getSelectedRow();

        txtBarCode.setText(model.getValueAt(selectRowIndex, 0).toString());
        txtName.setText(model.getValueAt(selectRowIndex, 9).toString());
        txtPrice.setText(model.getValueAt(selectRowIndex, 3).toString());
    }//GEN-LAST:event_tblCustMedMouseClicked

    private void tblCustFeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustFeedMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblCustFeed.getModel();
        int selectRowIndex = tblCustFeed.getSelectedRow();

        txtBarCode.setText(model.getValueAt(selectRowIndex, 0).toString());
        txtName.setText(model.getValueAt(selectRowIndex, 1).toString());
        txtPrice.setText(model.getValueAt(selectRowIndex, 5).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustFeedMouseClicked

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCustFeedCon;
    private javax.swing.JButton btnCustMedCon;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCustFeed;
    private javax.swing.JTable tblCustMed;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtBarCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
