/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package antprogram;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author Administrator
 */
public class SignUPForm extends javax.swing.JFrame {

    private CustomerBLL custbll;
    private CustomerDAL custdal;
    private VetrinaryBLL vetbll;
    private VetrinaryDAL vetdal;
    Connection con ;

    /**
     * Creates new form SignUPForm
     */
    public SignUPForm() {
        initComponents();
    }
    public SignUPForm(Connection con){
        this();
    this.con = con;
    }

    public SignUPForm(CustomerBLL custbll, VetrinaryBLL vetbll) {
        this();
        this.custbll = custbll;
        this.vetbll = vetbll;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        radbtnCustomer = new javax.swing.JRadioButton();
        radbtnvetrinery = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        comBoxCity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 79));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 50, -1, 69));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("ID_NUMBER :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 47));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("FIRST_NAME :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 45));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("LAST_NAME :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 42));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("PHONE_NUMBER :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 43));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("ADDRESS :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 210, 46));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("CITY :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, 50));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 571, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 569, 20));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 571, -1));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 571, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 569, -1));

        btnSubmit.setBackground(new java.awt.Color(124, 193, 238));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 0, 81));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel3.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, 62));

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 81));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, -1, 62));

        buttonGroup1.add(radbtnCustomer);
        radbtnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        radbtnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        radbtnCustomer.setText("CUSTOMER");
        radbtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(radbtnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 78, 210, 69));

        buttonGroup1.add(radbtnvetrinery);
        radbtnvetrinery.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        radbtnvetrinery.setForeground(new java.awt.Color(255, 255, 255));
        radbtnvetrinery.setText("VETRINARY");
        radbtnvetrinery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnvetrineryActionPerformed(evt);
            }
        });
        jPanel3.add(radbtnvetrinery, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, 69));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SIGN_UP FORM..");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 319, 66));

        comBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cairo", "giza", "minya", "assiut", "sohag", "qena", "hurghada", "other" }));
        comBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCityActionPerformed(evt);
            }
        });
        jPanel3.add(comBoxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 569, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PASSWORD :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, 30));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 570, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
//        CustomerBLL custBLL = new CustomerBLL();
//        Customer cust = null;
//
//        if (radbtnCustomer.isSelected()) {
//
//            try {
//                cust = new Customer(new DBConnection());
//            } catch (SQLException ex) {
//                java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//
//            cust.setCustomerID(txtID.getText());
//            cust.setCustomerFirstname(txtFirstName.getText());
//            cust.setCustomerLastName(txtLastName.getText());
//            cust.setCustomerPhone(txtPhone.getText());
//            cust.setCustomerAddress(txtAddress.getText());
//            cust.setCustomerCity(comBoxCity.getSelectedItem().toString());
//            cust.setCustomerPassword(txtPassword.getText());
//
//            try {
//                custBLL.createCustomer(cust);
//
//            } catch (BusinessException ex) {
//                java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//            if (radbtnvetrinery.isSelected()) {
//                Vetrinary vet = null;
//                try {
//                    vet = new Vetrinary(new DBConnection());
//                } catch (SQLException ex) {
//                    java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                }
//                VetrinaryBLL vetBLL = new VetrinaryBLL();
//                vet.setVetID(txtID.getText());
//                vet.setVetFirstName(txtFirstName.getText());
//                vet.setVetLastName(txtLastName.getText());
//                vet.setVetPhone(txtPhone.getText());
//                vet.setVetAddress(txtAddress.getText());
//                vet.setVetCity(comBoxCity.getSelectedItem().toString());
//                try {
//                    vetBLL.createVetrinary(vet);
//                } catch (Exception ex) {
//                    ex.printStackTrace();
//                }
//            }

        if (radbtnCustomer.isSelected()) {
            String ID = txtID.getText();
            String fname = txtFirstName.getText();
            String lname = txtLastName.getText();
            String phone = txtPhone.getText();
            String address = txtAddress.getText();
            String city = comBoxCity.getSelectedItem().toString();
            String password = txtPassword.getText();
            String sql = "SELECT * FROM tblCustomer where customer_ID ='" + ID + "'";
            Statement stmt;
            
            try {
                stmt = con.createStatement();
                ResultSet results = stmt.executeQuery(sql);
                if (results.next()) {
                    JOptionPane.showMessageDialog(null, "This data already exists .");
                } else {
                    String sqlinsert = "INSERT INTO tblCustomer(customer_ID,first_name,last_name,phone_number,address,city,password) VALUES (?,?,?,?,?,?,?)";
                    try {
                        PreparedStatement ps = con.prepareStatement(sqlinsert);
                        ps.setString(1, ID);
                        ps.setString(2, fname);
                        ps.setString(3, lname);
                        ps.setString(4, phone);
                        ps.setString(5, address);
                        ps.setString(6, city);
                        ps.setString(7, password);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "You have successfully created an account");
                        LoginForm log = new LoginForm(con);
                        dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());

                    }
                }

            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }
        if (radbtnvetrinery.isSelected()) {
            String ID = txtID.getText();
            String fname = txtFirstName.getText();
            String lname = txtLastName.getText();
            String phone = txtPhone.getText();
            String address = txtAddress.getText();
            String city = comBoxCity.getSelectedItem().toString();
            String password = txtPassword.getText();
            String sql = "SELECT * FROM tblVetrinary where ID ='" + ID + "'";
            Statement stmt;
            
            try {
                stmt = con.createStatement();
                ResultSet results = stmt.executeQuery(sql);
                if (results.next()) {
                    JOptionPane.showMessageDialog(null, "This data already exists .");
                } else {
                    String sqlinsert = "INSERT INTO tblVetrinary(ID,first_name,last_name,phone_number,address,city,password) VALUES (?,?,?,?,?,?,?)";
                    try {
                        PreparedStatement ps = con.prepareStatement(sqlinsert);
                        ps.setString(1, ID);
                        ps.setString(2, fname);
                        ps.setString(3, lname);
                        ps.setString(4, phone);
                        ps.setString(5, address);
                        ps.setString(6, city);
                        ps.setString(7, password);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "You have successfully created an account");
                        LoginForm log = new LoginForm(con);
                        dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());

                    }
                }

            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void radbtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnCustomerActionPerformed

    private void comBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void radbtnvetrineryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnvetrineryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnvetrineryActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        OuterForm outer = new OuterForm();

        outer.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUPForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comBoxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radbtnCustomer;
    private javax.swing.JRadioButton radbtnvetrinery;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
