/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package antprogram;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class VetHomeForm extends javax.swing.JFrame {
Connection con ;
    /**
     * Creates new form VetHomeForm
     */
    public VetHomeForm() {
        initComponents();
    }
        public VetHomeForm(Connection con) {
        this();
        this.con=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewMedFeed = new javax.swing.JButton();
        btnViewMedProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewFeed = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewMed = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        radbtnFeedFactory = new javax.swing.JRadioButton();
        radbtnVetCompany = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLisence = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboxCity = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnRefreash = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMedBarCode = new javax.swing.JTextField();
        txtMedSellingPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMedQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMedPurchasePrice = new javax.swing.JTextField();
        btnMedConnect = new javax.swing.JButton();
        btnMedInsert = new javax.swing.JButton();
        btnMedUpdate = new javax.swing.JButton();
        btnMedDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtFeedName = new javax.swing.JTextField();
        txtFeedQuantity = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFeedPurchasePrice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFeedSize = new javax.swing.JTextField();
        txtFeedSellingPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFeedBarCode = new javax.swing.JTextField();
        btnFeedConnect = new javax.swing.JButton();
        btnFeedInsert = new javax.swing.JButton();
        btnFeedUpdate = new javax.swing.JButton();
        btnFeedDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEDICINE..");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FEED..");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 250, 60));

        btnViewMedFeed.setBackground(new java.awt.Color(124, 193, 238));
        btnViewMedFeed.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnViewMedFeed.setForeground(new java.awt.Color(0, 0, 81));
        btnViewMedFeed.setText("CONNECT TO DATA BASE");
        btnViewMedFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedFeedActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedFeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        btnViewMedProd.setBackground(new java.awt.Color(124, 193, 238));
        btnViewMedProd.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnViewMedProd.setForeground(new java.awt.Color(0, 0, 81));
        btnViewMedProd.setText("CONNECT TO DATA BASE");
        btnViewMedProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        tblViewFeed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViewFeed);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1195, 220));

        tblViewMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblViewMed);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1195, 230));

        jTabbedPane1.addTab("VIEW PRODUCTS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(radbtnFeedFactory);
        radbtnFeedFactory.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        radbtnFeedFactory.setForeground(new java.awt.Color(255, 255, 255));
        radbtnFeedFactory.setText("FEED_FACTORY");
        jPanel2.add(radbtnFeedFactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 45, -1, -1));

        buttonGroup1.add(radbtnVetCompany);
        radbtnVetCompany.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        radbtnVetCompany.setForeground(new java.awt.Color(255, 255, 255));
        radbtnVetCompany.setText("VET_COMPANY");
        jPanel2.add(radbtnVetCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 43, -1, -1));

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSupplier);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, 1220, 159));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LICENSE :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NAME :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel2.add(txtLisence, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 272, 470, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 470, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PHONE_NUMBER :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 340, 30));
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 350, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADDRESS :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CITY :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        comboxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cairo", "giza", "minya", "assiut", "sohag", "qena", "hurghada", "other" }));
        comboxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCityActionPerformed(evt);
            }
        });
        jPanel2.add(comboxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 392, 470, 30));

        btnDelete.setBackground(new java.awt.Color(124, 193, 238));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 81));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, -1, -1));

        btnRefreash.setBackground(new java.awt.Color(124, 193, 238));
        btnRefreash.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnRefreash.setForeground(new java.awt.Color(0, 0, 81));
        btnRefreash.setText("REFREASH");
        btnRefreash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreashActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefreash, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        btnInsert.setBackground(new java.awt.Color(124, 193, 238));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(0, 0, 81));
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(124, 193, 238));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 81));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        jTabbedPane1.addTab("THE SUPPLIERS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 79));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1250, 285));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NAME :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jPanel3.add(txtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 410, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BAR_CODE :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));
        jPanel3.add(txtMedBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 400, 30));

        txtMedSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedSellingPriceActionPerformed(evt);
            }
        });
        jPanel3.add(txtMedSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 400, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SELLING_PRICE :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        txtMedQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedQuantityActionPerformed(evt);
            }
        });
        jPanel3.add(txtMedQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 410, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUANTITY :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PURCHASE_PRICE :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        txtMedPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedPurchasePriceActionPerformed(evt);
            }
        });
        jPanel3.add(txtMedPurchasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 410, 30));

        btnMedConnect.setBackground(new java.awt.Color(124, 193, 238));
        btnMedConnect.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnMedConnect.setForeground(new java.awt.Color(0, 0, 81));
        btnMedConnect.setText("REFREASH");
        btnMedConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedConnectActionPerformed(evt);
            }
        });
        jPanel3.add(btnMedConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        btnMedInsert.setBackground(new java.awt.Color(124, 193, 238));
        btnMedInsert.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnMedInsert.setForeground(new java.awt.Color(0, 0, 81));
        btnMedInsert.setText("INSERT");
        btnMedInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedInsertActionPerformed(evt);
            }
        });
        jPanel3.add(btnMedInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        btnMedUpdate.setBackground(new java.awt.Color(124, 193, 238));
        btnMedUpdate.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnMedUpdate.setForeground(new java.awt.Color(0, 0, 81));
        btnMedUpdate.setText("UPDATE");
        btnMedUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnMedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        btnMedDelete.setBackground(new java.awt.Color(124, 193, 238));
        btnMedDelete.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnMedDelete.setForeground(new java.awt.Color(0, 0, 81));
        btnMedDelete.setText("DELETE");
        btnMedDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnMedDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, -1, -1));

        jTabbedPane1.addTab("UPDATE MEDICINE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 79));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("NAME :");

        txtFeedQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedQuantityActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("QUANTITY :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PURCHASE_PRICE :");

        txtFeedPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedPurchasePriceActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("SIZE :");

        txtFeedSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedSizeActionPerformed(evt);
            }
        });

        txtFeedSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedSellingPriceActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SELLING_PRICE :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BAR_CODE :");

        btnFeedConnect.setBackground(new java.awt.Color(124, 193, 238));
        btnFeedConnect.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnFeedConnect.setForeground(new java.awt.Color(0, 0, 81));
        btnFeedConnect.setText("REFREASH");
        btnFeedConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedConnectActionPerformed(evt);
            }
        });

        btnFeedInsert.setBackground(new java.awt.Color(124, 193, 238));
        btnFeedInsert.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnFeedInsert.setForeground(new java.awt.Color(0, 0, 81));
        btnFeedInsert.setText("INSERT");
        btnFeedInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedInsertActionPerformed(evt);
            }
        });

        btnFeedUpdate.setBackground(new java.awt.Color(124, 193, 238));
        btnFeedUpdate.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnFeedUpdate.setForeground(new java.awt.Color(0, 0, 81));
        btnFeedUpdate.setText("UPDATE");
        btnFeedUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedUpdateActionPerformed(evt);
            }
        });

        btnFeedDelete.setBackground(new java.awt.Color(124, 193, 238));
        btnFeedDelete.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnFeedDelete.setForeground(new java.awt.Color(0, 0, 81));
        btnFeedDelete.setText("DELETE");
        btnFeedDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14)
                                .addGap(114, 114, 114)
                                .addComponent(txtFeedName, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel16)
                                .addGap(34, 34, 34)
                                .addComponent(txtFeedBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(94, 94, 94)
                                .addComponent(txtFeedQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel17)
                                .addGap(5, 5, 5)
                                .addComponent(txtFeedSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(15, 15, 15)
                                .addComponent(txtFeedPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel19)
                                .addGap(67, 67, 67)
                                .addComponent(txtFeedSize, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFeedConnect)
                .addGap(152, 152, 152)
                .addComponent(btnFeedInsert)
                .addGap(215, 215, 215)
                .addComponent(btnFeedUpdate)
                .addGap(252, 252, 252)
                .addComponent(btnFeedDelete)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtFeedName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtFeedBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtFeedQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtFeedSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtFeedPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addComponent(txtFeedSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFeedConnect)
                    .addComponent(btnFeedInsert)
                    .addComponent(btnFeedUpdate)
                    .addComponent(btnFeedDelete))
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("UPDATE FEED", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void comboxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCityActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreashActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtMedSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedSellingPriceActionPerformed

    private void txtMedQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedQuantityActionPerformed

    private void txtMedPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedPurchasePriceActionPerformed

    private void btnMedConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedConnectActionPerformed

    private void btnMedInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedInsertActionPerformed

    private void btnMedUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedUpdateActionPerformed

    private void btnMedDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedDeleteActionPerformed

    private void txtFeedQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedQuantityActionPerformed

    private void txtFeedPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedPurchasePriceActionPerformed

    private void txtFeedSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedSizeActionPerformed

    private void txtFeedSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedSellingPriceActionPerformed

    private void btnFeedConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeedConnectActionPerformed

    private void btnFeedInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeedInsertActionPerformed

    private void btnFeedUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeedUpdateActionPerformed

    private void btnFeedDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeedDeleteActionPerformed

    private void btnViewMedProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedProdActionPerformed
  Medicine med = new Medicine();
        DefaultTableModel model = (DefaultTableModel) tblViewMed.getModel();
        model.setRowCount(0);
        MedicineBLL medBLL = new MedicineBLL();
        try {
            medBLL.getAllMedicine();
        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMedProdActionPerformed

    private void btnViewMedFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedFeedActionPerformed
 Feed fed = new Feed();
        DefaultTableModel model = (DefaultTableModel) tblViewFeed.getModel();
        model.setRowCount(0);
        FeedBLL fedBLL = new FeedBLL();
        try {
            fedBLL.getAllFeeds();
        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMedFeedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetHomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFeedConnect;
    private javax.swing.JButton btnFeedDelete;
    private javax.swing.JButton btnFeedInsert;
    private javax.swing.JButton btnFeedUpdate;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnMedConnect;
    private javax.swing.JButton btnMedDelete;
    private javax.swing.JButton btnMedInsert;
    private javax.swing.JButton btnMedUpdate;
    private javax.swing.JButton btnRefreash;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewMedFeed;
    private javax.swing.JButton btnViewMedProd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboxCity;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JRadioButton radbtnFeedFactory;
    private javax.swing.JRadioButton radbtnVetCompany;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTable tblViewFeed;
    private javax.swing.JTable tblViewMed;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFeedBarCode;
    private javax.swing.JTextField txtFeedName;
    private javax.swing.JTextField txtFeedPurchasePrice;
    private javax.swing.JTextField txtFeedQuantity;
    private javax.swing.JTextField txtFeedSellingPrice;
    private javax.swing.JTextField txtFeedSize;
    private javax.swing.JTextField txtLisence;
    private javax.swing.JTextField txtMedBarCode;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtMedPurchasePrice;
    private javax.swing.JTextField txtMedQuantity;
    private javax.swing.JTextField txtMedSellingPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
